# Generated by Django 5.1.5 on 2025-03-14 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_video_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50)),
                ('rating', models.IntegerField()),
                ('additional_comments', models.TextField()),
                ('feedback_target', models.CharField(blank=True, choices=[('insurance', 'Insurance'), ('lab', 'Lab'), ('pharmacy', 'Pharmacy'), ('doctor', 'Doctor')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'db_table': 'Feedback_details',
            },
        ),
    ]
