# Generated by Django 5.1.5 on 2025-03-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='feedback_target',
        ),
    ]
